# Generated by Django 5.1.1 on 2024-09-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
